services:
  app:
    image: docker.io/jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /home/hades/dockers/npm/data:/data
      - /home/hades/dockers/npm/letsencrypt:/etc/letsencrypt
